# Deployment 는 apps 로 버전 명시
apiVersion : apps/v1
kind: Deployment

# 기본 데이터 주입
metadata:
  name: spring-deployment

# 레플리카스 로 Pod 개수 명시 (만약 서버 개수를 늘리고 싶을 때 그냥 숫자만 바꾸면 됨)
# Deployment 세부 정보
spec:
  replicas: 3

  selector:
    matchLabels:
      app : backend-app

# 배포할 Pod에 대항 정보 기입
  template:
    metadata:
      labels:
        app: backend-app

# 새로운 기능을 빌드하고 싶을 때 이미지 빌드하고 image 버전만 수정하면 된다.
    spec:
      containers:
        - name: spring-pod
          image: spring-server
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
