services:
  minio:
    image: minio/minio:latest
    container_name: minio_test
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ACCESS_KEY: minio
      MINIO_SECRET_KEY: minio123
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin123
    restart: unless-stopped
    volumes:
      - minio_data:/data
    command: server /data --console-address ":9001"
    networks:
      - minio_net

  mysql:
    image: mysql:8.0
    container_name: mysql-container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: minio_test
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "33306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - minio_net


volumes:
  mysql_data:
  minio_data:

networks:
  minio_net:
    driver: bridge