spring:
  application:
    name: minio-test

  servlet:
    session:
      timeout: 90m

  jwt:
    secret: secretKeydsa81821jdsad1jx

  datasource:
    url: jdbc:mysql://localhost:33306/StudyProject?createDatabaseIfNotExist=true
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect


# Minio server configuration
minio:
  server:
    url: ${MINIO_SERVER_URL:http://localhost:9000}
    access-key: ${MINIO_SERVER_ACCESS_KEY:minioadmin}
    secret-key: ${MINIO_SERVER_SECRET_KEY:minioadmin123}
    bucket: ${MINIO_BUCKET_NAME:files}

# Server Configuration
server:
  port: 8089
  address: 0.0.0.0